version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
      - api
    networks:
      - frontend
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
    ports:
      - "80:80"
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
  api:
    build: 
      context: './python'
    networks:
      - backend
      - frontend
    volumes:
      - ./python/api:/app/api
    container_name: api
    ports:
      - "5000:5000"
    restart: always
networks:
  frontend:
  backend:
volumes:
    data: