FROM python:3.8.0

WORKDIR /app
#RUN apk update && apk add python3-dev \
#                        gcc \
#                        libc-dev
                        
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . /app/

#RUN ["chmod", "+x", "./execute.sh"]

EXPOSE 5000

#ENTRYPOINT ["./execute.sh"]
